### ISSUE TITLE
I have find a Reflected XSS vulnerability in this project

### ISSUE THREAD

**Issue by jgj212** [FenixHosting/fenix-open-source#2]
Hello:
I have find a Reflected XSS vulnerability in this project.

The vulnerability exists due to insufficient filtration of user-supplied data in "search-by-topic" HTTP parameter that will be passed to "fenix-open-source-master\forums\search.php". The infected source code is line 68, there is no protection on $_GET["search-by-topic"]; if $_GET["search-by-topic"] contains evil js code, line 68 will trigger untrusted code to be excuted on the browser side.
![code1](https://cloud.githubusercontent.com/assets/1484292/23579566/22ea84ea-012b-11e7-8b7d-5cf1b2120749.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/fenix-open-source-master/forums/search.php?search-by-topic="><script>alert(1);</script><"

The follow scrrenshot is the result to click the upper url ( win7 spq x64 + firefox 51.0.1 32bit ):
![sc](https://cloud.githubusercontent.com/assets/1484292/23579603/b49a150e-012b-11e7-8d3f-2eb3d22c87d3.png)

Discoverer: Haojun Hou, DongWang in ADLab of Venustech

**Comment by RubeVi** [comment]
Hello and thanks for reporting the issue.
I've pushed 310f21204eaa53956bf1deb090a4a4ba1dbda632

**Comment by RubeVi** [comment]
Can i contact you via skype?

**Comment by jgj212** [comment]
@RubeVi i do not have skype. how about google hangouts? My google hangouts is jgj212@gmail.com
